### ISSUE TITLE
Error running methylpy paired-end-alignment

### ISSUE THREAD

**Issue by olmath** [yupenghe/methylpy#29] opened 2019-03-26 14:49 UTC
Hi Yupeng,

I am very much interested in trying using Methylpy, but I am not familiar with Python and I am stuck with an error that I am not able to fix. 

I am running this command:
```
$ methylpy paired-end-pipeline --read1-files FCH2N2NBBXY_L7_ARAsbmMAAAAAAA-9_1.fq.gz --read2-files FCH2N2NBBXY_L7_ARAsbmMAAAAAAA-9_2.fq.gz --sample L5_0mM_minimap2 --forward-ref L5_background_one_T-DNA_minimap_f.mmi --reverse-ref L5_background_one_T-DNA_minimap_r.mmi --ref-fasta L5_background_one_T-DNA.fa --compress-output T --num-procs 4 --trim-reads F --check-dependency T --generate-mpileup-file F --aligner minimap2
```

and get the following error (using either minimap2 or bowtie2 as an aligner):
```
Traceback (most recent call last):
  File "/usr/local/bin/methylpy", line 5, in <module>
    parse_args()
  File "/Library/Python/2.7/site-packages/methylpy/parser.py", line 185, in parse_args
    keep_temp_files=args.keep_temp_files)
  File "/Library/Python/2.7/site-packages/methylpy/call_mc_pe.py", line 342, in run_methylation_pipeline_pe
    keep_temp_files=keep_temp_files)
  File "/Library/Python/2.7/site-packages/methylpy/call_mc_pe.py", line 1370, in call_methylated_sites_pe
    keep_temp_files = keep_temp_files)
  File "/Library/Python/2.7/site-packages/methylpy/call_mc_se.py", line 1498, in call_methylated_sites
    +" -q "+str(min_mapq)+" -B -f "+reference_fasta+" "+inputf
TypeError: bad operand type for unary +: 'str' 
```

Here is what I get when running the methylpy test:
```Tests start
Tue Mar 26 15:32:35 2019

Test importing methylpy module.
- importing call_mc_se: pass
- importing call_mc_pe: pass
- importing DMRfind: pass
- importing parser: pass
Check methylpy executable:pass

methylpy is successfully installed!

Check whether dependencies are available in PATH
- find bowtie: failed
- find bowtie2: found version 2.2.6
- find minimap2: found version 2.16-r922
- find samtools: found version 1.9
- find cutadapt: failed
- find java: found version 1.6.0_65
Only bowtie2 is available. Skip tests for bowtie related code

Test DMRfind: failed
Test reidentify-DMR: failed

Test build-reference with bowtie2: pass
Test build-reference with minimap2: pass

Test single-end-pipeline with bowtie2: pass
Test single-end-pipeline with minimap2: pass

Test paired-end-pipeline with bowtie2: pass
Test paired-end-pipeline with minimap2: pass

Test quality filter for BAM file of single-end data: pass

Test call-methylation-state for single-end data: pass
Test call-methylation-state for paired-end data: pass

Test merge-allc: pass

Test filter-allc: pass

All tests are done!
Tue Mar 26 15:34:09 2019
The tests took 94.28 seconds!
``` 

Many thanks for your help!

**Comment by yupenghe** [comment] 2019-03-27 01:39
Is it possible for me to have a small test example for reproducing the error?

What are the files generated? What are the sizes of those files?

**Comment by olmath** [comment] 2019-03-27 09:30
Many thanks for your swift reply.

Enclosed are 2 fastq test files, together the fasta file I used to generate the minimap2 index, with which I get the same error. 

Here are the command lines I used:
```
methylpy build-reference --input-files Chr1.fa --output Chr1_minimap --aligner minimap2
```
```
methylpy paired-end-pipeline --read1-files fastq_test1.fq.gz --read2-files fastq_test2.fq.gz --sample test --forward-ref Chr1_minimap_f.mmi --reverse-ref Chr1_minimap_r.mmi --ref-fasta Chr1.fa --compress-output T --num-procs 4 --trim-reads F --check-dependency T --generate-mpileup-file F --aligner minimap2 --keep-temp-files T
```

The script generates the following files:
test_libA_forward_strand_hits.sam
test_libA_reverse_strand_hits.sam
test_processed_reads.bam
test_processed_reads.bam.read2flipped.bam
test_processed_reads.bam.read2flipped.bam.bai

When using the full .fastq files, similar files where generated, and these files where of pretty big size (Gb for the sam files)

Also, I noticed that, tests for DMRfind and reidentify-DMR failed when running the methylpy test. Is that a problem?

[fastq_test1.fq.gz](https://github.com/yupenghe/methylpy/files/3012256/fastq_test1.fq.gz)
[fastq_test2.fq.gz](https://github.com/yupenghe/methylpy/files/3012257/fastq_test2.fq.gz)
[Chr1.fa.gz](https://github.com/yupenghe/methylpy/files/3012431/Chr1.fa.gz)

**Comment by yupenghe** [comment] 2019-03-28 04:19
Hey it was due to a bug. It should be fixed now. Can you update methylpy to 1.3.6 using pip and try if that fix the problem?

By the way, for the samples you already processed, you should be able to start from midway using the  `methylpy call-methylation-state` command. 

For the failure on DMRfind and reidentify-DMR, can you share the error message files (`test_error_msg.txt`)?

**Comment by olmath** [comment] 2019-03-28 10:02
Hey,

I have updated to 1.3.6 and it seems to work fine now. I am not sure how many files the pipeline should produce as an output; I got 2 files, the allC.tsv.gz and the allC index file. 

As for the failure on DMRfind and reidentify-DMR, please find the test_error_msg.txt file.
 
Many thanks again for your fast reply and your kind help. I very much appreciate.
[test_error_msg.txt](https://github.com/yupenghe/methylpy/files/3017010/test_error_msg.txt)

**Comment by olmath** [comment] 2019-03-28 13:18
Hi again,

Correction to my previous comment, I also got the .bam file as an output. 

Running the script on the full fastq files and looking at the allC file seems to work properly using bowtie2 but not using minimap2 as the aligner. When using minimap2, the 5th column is always 0. 
```
Chr1    3879    +       CAA     0       16      1
Chr1    3882    +       CAT     0       16      1
Chr1    3885    +       CTG     0       20      1
Chr1    3887    -       CAG     0       3       1
Chr1    3890    -       CTA     0       3       1
Chr1    3891    +       CTA     0       24      1
Chr1    3894    +       CGA     0       24      1
```
Running call-methylation-state on the bam file generated using minimap2 produces the following error :
```
methylpy call-methylation-state --input-file allc_L5_0mM.tsv.gz --paired-end T --sample L5_0mMrecall --ref-fasta L5_background_one_T-DNA.fa --num-procs 4
Begin flipping the strand of read 2
Thu Mar 28 11:10:12 2019

[E::sam_parse1] missing SAM header
[W::sam_read1] Parse error at line 1
[main_samview] truncated file.
Input not indexed. Indexing...
Thu Mar 28 11:10:12 2019

[mpileup] 1 samples in 1 input files
```

And one (maybe stupid) question:
How to setup "allc-to-bigwig" parameters when both the allC and the genome fasta files use "Chr" for the chromosome prefix and one wants to keep it as such in the bigwig output?

Many thanks for all your help!

**Comment by yupenghe** [comment] 2019-03-29 04:14
I need to do more tests to support minimap2. I would recommend using bowtie2 for now. 

I don't think you will need special option for running "allc-to-bigwig". "Chr" will be kept. Only the lowercase "chr" may need extra attention because by default the "chr" is removed.

**Comment by yupenghe** [comment] 2019-03-29 04:16
> Hey,
> 
> I have updated to 1.3.6 and it seems to work fine now. I am not sure how many files the pipeline should produce as an output; I got 2 files, the allC.tsv.gz and the allC index file.
> 
> As for the failure on DMRfind and reidentify-DMR, please find the test_error_msg.txt file.
> 
> Many thanks again for your fast reply and your kind help. I very much appreciate.
> [test_error_msg.txt](https://github.com/yupenghe/methylpy/files/3017010/test_error_msg.txt)

It seems that you will need to install the GSL library (or add the path to LD_LIBRARY_PATH if it has been installed). See https://github.com/yupenghe/methylpy#optional-step---compile-rmscpp

**Comment by olmath** [comment] 2019-03-29 09:08
Hey,

I have tried to run "allc-to-bigwig" with all possible option settings and couldn't make it to get a bigwig file with "Chr" that would display properly in IGV. However, my allC files also contains "mitochondria" and "chloroplast" chromosomes, and data for those display properly using  "allc-to-bigwig" default settings.

As for the failure on DMRfind, I don't have informatics background and  I am also totally lost... 
I have the GSL library installed and (I think) added to the LD_LIBRARY_PATH. Here is what I have in my profile
`
export LD_LIBRARY_PATH="/usr/local/Cellar/gsl/2.5/lib/:"$LD_LIBRARY_PATH
`
`
export CXXFLAGS="-g -O3 -I/usr/local/Cellar/gsl/2.5/include/gsl/ -L/usr/local/Cellar/gsl/2.5/lib/"
`

I have have tried this command `$ ./run_rms_tests.out` in the methylpy directory and got this :
```
-bash: ./run_rms_tests.out: cannot execute binary file
```

Then I've tried the "compile the rms.cpp"  thing, using this command 
``
$ g++ -O3 -l gsl -l gslcblas -o run_rms_tests.out rms.cpp
``
and got this error
```
rms.cpp:88:1: warning: control reaches end of non-void function [-Wreturn-type]
}
^
1 warning generated.
ld: can't write output file: run_rms_tests.out for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I have no idea what to do

**Comment by yupenghe** [comment] 2019-03-29 16:57
Sorry about that. The "allc-to-bigwig" was due to that methylpy could not properly handle the "Chr" prefix for chromosomes. The reason that mitochondria and chloroplast worked is because their chromosome names starts with "chr" or does not contain "chr". I will try to fix the problem for Chr with some code change. 

The failure mode of DMRfind is new to me. You did the right fix. Just one thing. When you ran the command `g++ -O3 -l gsl -l gslcblas -o run_rms_tests.out rms.cpp`, did you have written permission on that directory? Lack of written permission looks like the cause of the compiling error. You may use sudo to compile it or just change the permission of that folder such that you have written permission.

**Comment by yupenghe** [comment] 2019-03-29 22:38
> Hey,
> 
> I have tried to run "allc-to-bigwig" with all possible option settings and couldn't make it to get a bigwig file with "Chr" that would display properly in IGV. However, my allC files also contains "mitochondria" and "chloroplast" chromosomes, and data for those display properly using "allc-to-bigwig" default settings.
> 

Can you try if you still have trouble using "allc-to-bigwig" in the updated methylpy (1.3.7)?

**Comment by olmath** [comment] 2019-04-01 08:14
After updating to methylpy 1.3.7 and playing with the different options, I am afraid I am still unable to generate bigwig files with "Chr" as the chromosome prefix.
Regarding DMRfind, I've compiled the rms.cpp file as sudo and it did fix the problem. Thank you

**Comment by olmath** [comment] 2019-04-01 16:09
Hey Yupeng

I still cannot generate BIGWIG files with "Chr" as the chromosome prefix after updating to methylpy 1.3.7. 

I noticed another issue, unrelated (I think) to "allc-to-bigwig":

I obtain inconsistent methylation levels when running "call-methylation-state" on a BAM file obtained from another pipeline (bs-seeker2) with the command line below:
```
methylpy call-methylation-state --input-file ../WT.bam_sorted.bam --sample WT_bsseeker2 --ref-fasta genome.fa --paired-end T --num-procs 4
```
The obtained methylation levels (bottom track on the IGV snapshot below) are way too high compared to what is known and expected (top track on the IGV snapshot).
When I run the `methylpy paired-end-pipeline` on the same fastq files that were used with `bsseeker2`, I get methylation values that seem correct, but methylation values are absent from many genomic regions (compare top track and middle track on the IGV snapshot). It seems to me that sequences present in several highly similar copies in the genome (e.g. transposons) are excluded when analyzing the data with methylpy, while those are retained when analyzing the same data with bsseeker2 (there is transposon in the center of the IGV snapshot).  

I would very much prefer using methylpy in place of bsseeker2. Could you help me figuring out 
- how to proceed with using "call-methylation-state" on BAM files generated with bseeker2 (I have plenty of those) and 
- how to setup methylpy so that highly homologous sequences are not excluded from the analysis (I am interested in transposons...)

![Capture d’écran 2019-04-01 à 14 36 10](https://user-images.githubusercontent.com/18611136/55327959-83cdca00-548b-11e9-996f-4c21b78f4be1.png)

**Comment by yupenghe** [comment] 2019-04-02 01:11
Hey I just updated methylpy to 1.3.8 and the allc-to-bigwig issue should be resolved. 

I am not sure about the issue about bam from bseeker2. It may have some its own features that break the call-methylation-state. Did you try to run `call-methylation-state` with `--paired-end F`? If you can share one example of the bam, I can take a look. 

Mapping bisulfite data to transposons is tricky since the C->T conversion further reduces the already low sequence complexity of transposons. I don't have much experience on tuning aligner to allow multi-map reads and methylpy is not designed for handling reads on repeats . There is one option in methylpy you can try. `--merge-by-max-mapq` merges alignments on both forward and reverse reference in a more lenient way and ideally will increase mapping rate to allow for reads on transposons.

**Comment by olmath** [comment] 2019-04-02 16:03
Hey
The allc-to-bigwig issue is fixed indeed. Thanks! 

About calling methylation from bam outputs of bsseeker2, I have tried running `call-methylation-state` with `--paired-end F` but this does not help. I am not sure how to provide you with a bam file obtained with bsseeker2 as the files are rather big. Below is a head of such a file;  I also enclose a subsample of the file.
[TEST_bsseeker2.bam.gz](https://github.com/yupenghe/methylpy/files/3034879/TEST_bsseeker2.bam.gz)

```
K00133:507:H2N2NBBXY:7:1211:24322:34776	67	Chr1	1	255	38S62M	=	136	0	ATTGTTCTTTTTCTAAATTCTAAATTCTAAACATTAAATTTTAAATTTTAAATTTTAAATTTTAAATTTCTGAATTTTTAATTTTTAAATTTTTAAATTT	*	XO:Z:+FR	XS:i:0	NM:i:0	XM:Z:zzz----zzz----zzz----zzz----zz-Y-----zz-----zzz-----zzz-----z-	XG:Z:NN_CCCTAAACCCTAAACCCTAAACCCTAAACCTCTGAATCCTTAATCCCTAAATCCCTAAATCT_TT
K00133:507:H2N2NBBXY:7:1104:4411:14449	115	Chr1	1	255	43S57M	=	1	0	ATTCAATTATTCTTTTCCTAAACCCTAAACCCTAAACACTAAACCCTAAACCCTAAACCCTAAACCCTAAACCTCTAAATCCTTAATCCCTAAATCCCTA	*	XO:Z:-FR	XS:i:0	NM:i:0	XM:Z:-----------------------y---------------------------------	XG:Z:TT_TAGGGATTTAGGGATTAAGGATTCAGAGGTTTAGGGTTTAGGGTTTAGGGTTTAGGG_NN
K00133:507:H2N2NBBXY:7:1104:4411:14449	179	Chr1	1	255	33S30M1D12M1D7M18S	=	1	0	CTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACTCTAAATAAAACACAGTXO:Z:-FR	XS:i:0	NM:i:4	XM:Z:-----------------y---------------------------------	XG:Z:GA_TTTAGGGATTAAGGATTCAGAGGTTTAGGGTTTAGGGTTTAGGGTTTAGGG_NN
K00133:507:H2N2NBBXY:7:1104:3782:14695	115	Chr1	1	255	43S57M	=	1	0	ATTCAATTATTCTTTTCCTAAACCCTAAACCCTAAACACTAAACCCTAAACCCTAAACCCTAAACCCTAAACCTCTAAATCCTTAATCCCTAAATCCCTA	*	XO:Z:-FR	XS:i:0	NM:i:0	XM:Z:-----------------------y---------------------------------	XG:Z:TT_TAGGGATTTAGGGATTAAGGATTCAGAGGTTTAGGGTTTAGGGTTTAGGGTTTAGGG_NN
K00133:507:H2N2NBBXY:7:1104:3782:14695	179	Chr1	1	255	19S30M1D12M1D7M32S	=	1	0	CTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCCAAACCCTAAACCCTAAATAAAACACACTXO:Z:-FR	XS:i:0	NM:i:4	XM:Z:-----------------y---------------------------------	XG:Z:GA_TTTAGGGATTAAGGATTCAGAGGTTTAGGGTTTAGGGTTTAGGGTTTAGGG_NN
K00133:507:H2N2NBBXY:7:1220:15067:9350	115	Chr1	1	255	4S96M	=	1	0	TAAACCCTAAACCCTAAACCCTAAACCCTAAACCTCTGAATCCTTAATCCCTAAATCCCTAAATCTTTAAATCCTACATCCATAAATCCCTAAATACCTA	*	XO:Z:-FR	XS:i:0	NM:i:0	XM:Z:----------------z---------------------------------------------Y---------------------------------	XG:Z:AT_TAGGTATTTAGGGATTCATGGATGTAGGATTTAAAGATTTAGGGATTTAGGGATTAAGGATTCAGAGGTTTAGGGTTTAGGGTTTAGGGTTTAGGG_NN
K00133:507:H2N2NBBXY:7:1220:15067:9350	179	Chr1	1	255	12S30M1D5M53S	=	1	0	CTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACACCACACTACAAAATCAATCAAACCACTATACCAAACAATAGATAAAACCGA	*	XO:Z:-FR	XS:i:0	NM:i:1	XM:Z:--y---------------------------------	XG:Z:GA_TTCAGAGGTTTAGGGTTTAGGGTTTAGGGTTTAGGG_NN
K00133:507:H2N2NBBXY:7:1227:22891:7293	179	Chr1	1	255	57S43M	=	111	0	CAAATCACATCCGAATTCAATTGTTCTTTTCCTAAACCCTAAACCCTAAACACTAAACCCTAAACCCTAAACCCTAAACCCTAAACCTCTAAATCCTTAA	*	XO:Z:-FR	XS:i:0	NM:i:0	XM:Z:---------y---------------------------------	XG:Z:GA_TTAAGGATTCAGAGGTTTAGGGTTTAGGGTTTAGGGTTTAGGG_NN
K00133:507:H2N2NBBXY:7:2102:26971:43374	115	Chr1	1	255	21S79M	=	1	0	CCCTAAACCCTAAACACTAAACCCTAAACCCTAAACCCTAAACCCTAAACCTCTGAATCCTTAATCCCTAAATCCCTAAATCTTTAAATCCTACATCCAT	*	XO:Z:-FR	XS:i:0	NM:i:0	XM:Z:---------------------------------------------Y---------------------------------	XG:Z:TC_ATGGATGTAGGATTTAAAGATTTAGGGATTTAGGGATTAAGGATTCAGAGGTTTAGGGTTTAGGGTTTAGGGTTTAGGG_NN
K00133:507:H2N2NBBXY:7:2102:26971:43374	179	Chr1	1	255	30M1D12M1D8M50S	=	1	0	CCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAACCCTAAATAAAACTCTATAAAATCAATCATTACATTTTTCCATAAAATAGATAGCGCC	*	XO:Z:-FR	XS:i:0	NM:i:4	XM:Z:------------------y---------------------------------	XG:Z:GG_ATTTAGGGATTAAGGATTCAGAGGTTTAGGGTTTAGGGTTTAGGGTTTAGGG_NN
```

As for the transposon / missing regions issue, I have tried using '--merge-by-max-mapq' but the improvement is only marginal.  Alignments in bseeker2 and `methylpy` were both done using `bowtie2`, and bsseeker2 does not seem to work with multi mappers either, so I guess that the difference stems from the parameters that are passed to bowtie2, but I don't know what to change.
I think that it is possible that bsseeker2 may keep reads with multiple hits and assign those randomly to the different hits. Is there a way to get and keep reads with multiple hits randomly assigned in the methylpy analysis?

**Comment by yupenghe** [comment] 2019-04-03 05:59
Great. Glad the allc-to-bigwig works out. 

Just looked over the bam file you shared. Indeed, bseeker2 modified the bam file from bowtie2. It looks like that it flips the sequence and mapped strand of read 2 for its program to calculate methylation level. Unfortunately, methylpy is unable to handle this format. 

I found this set of bowtie2 options from bseeker2: "-D 50 -L 15 --score-min L,-0.6,-0.6". You may want to feed it to methylpy and check if it can recover the regions you are interested in.

In general, I don't think methylpy is able to process multi-mapped reads. It will throw out reads with multiple hits and only keep the uniquely mapped ones.

**Comment by olmath** [comment] 2019-04-03 13:25
> Great. Glad the allc-to-bigwig works out.
> 
> Just looked over the bam file you shared. Indeed, bseeker2 modified the bam file from bowtie2. It looks like that it flips the sequence and mapped strand of read 2 for its program to calculate methylation level. Unfortunately, methylpy is unable to handle this format.

Bummer!

> 
> I found this set of bowtie2 options from bseeker2: "-D 50 -L 15 --score-min L,-0.6,-0.6". You may want to feed it to methylpy and check if it can recover the regions you are interested in.
> 
> In general, I don't think methylpy is able to process multi-mapped reads. It will throw out reads with multiple hits and only keep the uniquely mapped ones.

I have tried passing these options to bowtie2 when running methylpy (which doubled mapping time!), unfortunately this has not allowed recovering more data along transposons. I am afraid I have to stick to bsseeker2 for the time being.

Many thanks for all your help , I very much appreciate.

**Closed as completed** 2019-04-04 05:10 UTC
